### ISSUE TITLE
bug: Android splash screen shifts (re-scales) as it transitions

### ISSUE THREAD

**Issue by ncoder** [ionic-team/capacitor#4478]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.4
  @capacitor/android 2.4.4
  @capacitor/core 2.4.4
  @capacitor/electron not installed

[success] Android looking great! �
```

### Platform(s)
Android
Pixel 4

### Current Behavior
If you use "androidScaleType": "CENTER_CROP" on your splash screen plugin config, the aspect ratio changes for the second part of the splashscreen display, but not the first, causing a noticeable shift.

### Expected Behavior
Splash screen should not visibly change during load.

### Code Reproduction
start with empty project, with suitably complete set of splashscreen images, 
then change the SplashScreen plugin configuration like so:

```json
    "plugins": {
        "SplashScreen": {
            "launchShowDuration": 3000,
            "androidScaleType": "CENTER_CROP",
            "showSpinner": true
        }
    },
```

Run on a Pixel 4.

### Other Technical Details

`npm --version` output:
6.14.4

`node --version` output:
v12.18.0

### Additional Context
https://github.com/ionic-team/capacitor/issues/1222
https://forum.ionicframework.com/t/bad-splashscreen-ratio-with-android-using-cli-new-feature/16159/20

**Comment by lincolnthree** [comment]
Yep, this happens on most or all of the android devices we've tested here, too.

**Comment by vanessag** [comment]
I am seeing the same issue as well. The only workaround I found was setting the initial screen to a static background color and not showing the splash image.

```
<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
    <item name="android:statusBarColor">#000000</item>
    <item name="android:navigationBarColor">#000000</item>
    <item name="android:background">#000000</item>
</style>
```
The drawback is that you get a blank screen without an image for about a second. If anyone has a better workaround let me know.

**Comment by lincolnthree** [comment]
@vanessag Thanks for this idea. Where in AndroidManifest.xml does that go? Cheers!

**Comment by vanessag** [comment]
@lincolnthree It goes in styles.xml.

**Comment by lincolnthree** [comment]
@vanessag Ah thank you. That explains where I went wrong :)

**Comment by oneclickwebstudio** [comment]
+1 scaling  splash screen is annoying.

**Comment by pbowyer** [comment]
I found this bug today. With `"androidScaleType": "CENTER_CROP"` set the splash screen works great on iOS and is squished when first loading on Android and then the proportions are corrected.

I recorded the screen and slowed it down. Note the extra problem with fullscreen - the splash screen doesn't resize to fill the whole screen.

![Splash redacted](https://user-images.githubusercontent.com/89852/134202217-2ecb2f76-4cf9-4f1b-b12e-8e9f19a76e04.gif)

My settings:
```json
		"SplashScreen": {
			"launchShowDuration": 2000,
			"backgroundColor": "#ffffffff",
			"splashFullScreen": true,
			"splashImmersive": true,
			"androidScaleType": "CENTER_CROP"
		}
```

And a fresh install today of `@capacitor/splash-screen@1.1.2`

**Comment by pbowyer** [comment]
I found https://forum.ionicframework.com/t/double-splash-screen-with-with-flash-in-between/187916/17?u=pbowyer which worked around the rescaling of the splash screen.

Setting `splashFullScreen: false` and `splashImmersive: false` doesn't fix the controls and status bar issue for me.

**Comment by alex-steinberg** [comment]
Several workaround suggestions here in the meantime https://github.com/ionic-team/capacitor/issues/1627 FYI

**Comment by bchehraz** [comment]
So I definitely had this issue on my app, but after ignoring it for a while, it seems to have gone away on Android 12 with `"@capacitor/cli": "^3.2.5",` and `"@capacitor/splash-screen": "^1.1.5"`. However on the same build, the bug still happens on Android 7.

**Comment by daviesdoclc** [comment]
Ugh. Just hit this problem today. Any work being done on this?

**Comment by bchehraz** [comment]
So in the past month I removed any use of the @capacitor/splash-screen API and made my own custom splash screen using css transitions. It doesn't totally fix the problem, where on Android the it shows a brief logo in the middle of the screen before triggering my custom splash screen and that logo is still slightly too wide. BUT since my custom splash screen has a fade-in and whole animation thing that is distinctly different looking than the <1 second showing a logo that is too wide, I think it's totally fine and not that noticeable.

**Comment by 77noox** [comment]
The solution I found to avoid both the resizing and the blank screen was to modify the activity tag in AndroidManifest.xml

from
`<activity ... android:theme="@style/AppTheme.NoActionBarLaunch">`
to
`<activity ... android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen">`

**Comment by jcesarmobile** [comment]
In Capacitor 4 if using the new Android 12 Splash Screen API (available in previous versions too with a support library) it no longer re scales.
There is still a problem of scaling in some devices, that can only be fixed by transitioning form using a background image to a splash icon what would be centered on the screen.
https://developer.android.com/develop/ui/views/launch/splash-screen
