### ISSUE TITLE
bug: service worker server.url not injecting capacitor

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/capacitor#5278]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/core: 3.3.2
```

### Current Behavior
Calling any native plugins when an app is served from an Angular service worker causes the plugins to fail. Using `server.url` to load the site on Android.
![image](https://user-images.githubusercontent.com/2852839/143595172-71102760-69e3-403f-afbc-058dce62e1cc.png)

Platform ready does not help for this. 

### Expected Behavior
Capacitor needs to be injected when a site is served through a service worker.

### Code Reproduction

app.module.ts
```
export function init_app(appLoadService: AppLoadService) {
  return () => appLoadService.initApp();
}

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule,
    ServiceWorkerModule.register('ngsw-worker.js', {
      enabled: environment.production,
      // Register the ServiceWorker as soon as the app is stable
      // or after 30 seconds (whichever comes first).
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ],
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    {
      provide: APP_INITIALIZER,
      useFactory: init_app,
      deps: [AppLoadService],
      multi: true,
    },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

app-load-service.ts
```
@Injectable({
  providedIn: 'root',
})
export class AppLoadService {
  constructor(
    private device: DeviceInfo,
    private platform: Platform
  ) {}

  async initApp(): Promise<any> {
    await this.platform.ready();

    SplashScreen.hide(); // breaks
  }
}
```

**Comment by dylanvdmerwe** [comment]
OR it seems that the capacitor script is not being injected after the site is served by a service worker. 

I have included this on Android but still getting plugin errors:
![image](https://user-images.githubusercontent.com/2852839/143600123-4ffb5f95-0386-4c63-814d-cd535243858d.png)

**Comment by webuniverseio** [comment]
Silly question, but for a workaround, it is possible to inject capacitor script manually?

**Comment by goforu** [comment]
The issue, anyone have a workaround?

**Comment by dylanvdmerwe** [comment]
Please see a repo here: https://github.com/happendev/TestCapacitor 

The PWA site is hosted on https://testapp.happen.zone.

**Comment by dylanvdmerwe** [comment]
When the Android app is first installed you can see Capacitor is working:
![image](https://user-images.githubusercontent.com/2852839/144424927-ab3a285a-5657-410d-9ac7-7884e626a8e7.png)

The site files are downloaded and served directly on first run:
![image](https://user-images.githubusercontent.com/2852839/144425080-1e5f7996-abb3-458d-9fa0-8241dc73c6e6.png)


When the app is launched the second time, Capacitor is not injected:
![image](https://user-images.githubusercontent.com/2852839/144425322-84ca66f3-8d20-45cc-8bd0-141e7f9dcecf.png)

The files are now served from the service worker:
![image](https://user-images.githubusercontent.com/2852839/144425625-e3f91a53-c29c-4342-8ec6-1ae4ad589b1a.png)

**Comment by dylanvdmerwe** [comment]
I have yet to do some additional testing, but I hope this issue is not the same on iOS.

**Comment by dylanvdmerwe** [comment]
@jcesarmobile is there anything I can do to assist with this?

**Comment by jgoux** [comment]
@dylanvdmerwe I started looking into what should be done in order to support this use case (I'll need it as well).

This is what we talked about with @thomasvidas on Discord : 

me : 
I think we need to introduce the ServiceWorkerClient in order to intercept requests from the service worker : https://stackoverflow.com/a/59606081 and https://stackoverflow.com/questions/62354423/how-to-use-serviceworkercontroller-on-android/63491172#63491172
The shouldInterceptRequest is the same as the WebviewClient's one so it should be a matter of calling them both

@thomasvidas : 
That seems pretty doable. I'd assume that WebViewLocalServer.shouldInterceptRequest() could be modified to check if it should serve from the service worker or from the normal local capacitor server.
Maybe it would be better to change bridge.getLocalServer()? But I'm more wary of that since this doesn't work on API 21-23 and I try to avoid touching the bridge if I can since it touches so much of the codebase.

@dylanvdmerwe Did you test on iOS a well?

**Comment by xEsk** [comment]
I'm facing this "problem" too....

As a temporary "workaround" (in order to solve this), I force a site reload when the ServiceWorker is Ready. I know and I also don't like the solution, but I needed to implement this 💩  while this "issue/bug/feature" is addressed.

```
if (Capacitor.isNativePlatform() && Capacitor.getPlatform() === 'android') {
  const reboot = localStorage.getItem('reboot')
  if (reboot !== '1') {
    localStorage.setItem('reboot', '1')
    setTimeout(() => location.reload(), 1)
  } else {
    localStorage.setItem('reboot', '0')
  }
}
```

Forgive me... 😂

**Comment by dylanvdmerwe** [comment]
Using this kind of functionality is primarily not for the app stores in our case, we really want to use this for apps that are rolled out (enterprise) to operators and employees at our clients. This would drastically reduce the building required to deploy updates to them, as all we would need to do is update the PWA.

Please advise if there is anything that I can do to assist or test to get `server.url` working for Android and iOS through a service worker on Capacitor.

**Comment by izeryab** [comment]
For every who face errors like "not implemented on android/ios" creating/installing a plugin you have to run `npx cap sync` when i was working for the first time on capacitor i was facing the error like "capacitorDialog is not implemented on Android" so i simply do `npx cap sync android` and it resolve the issue for me.

**Comment by dylanvdmerwe** [comment]
@jgoux Do you have any more feedback on the way forward on this? 

Has anyone tried anything further as we would think this kind of thing would be incredible to get working through Capacitor apps.

**Comment by jgoux** [comment]
@dylanvdmerwe Hello Dylan,

I didn't have time to investigate yet.

Did you already try this solution : https://stackoverflow.com/a/55916297/1728627 ?

**Comment by goforu** [comment]
> 

Nope, It's not working anymore.

**Comment by chrisharris77** [comment]
If the path your service worker is loading contains a ".html" file extension, the the following update in WebViewLocalServer.handleProxyRequest() resolves the issue. Note that this is exactly the same hack that is in WebViewLocalServer.handleLocalRequest(), so if it's good enough for local requests it should be good enough for proxy ones too.

               `if(request.getUrl().toString().contains(".html")) {
                    isHtmlText = true;
                } else {
                    for (Map.Entry<String, String> header : headers.entrySet()) {
                        if (header.getKey().equalsIgnoreCase("Accept") && header.getValue().toLowerCase().contains("text/html")) {
                            isHtmlText = true;
                            break;
                        }
                    }
                }`

**Comment by dylanvdmerwe** [comment]
@chrisharris77 No this does not appear to work, at least not when using a normal ionic app as per my repo. 

https://github.com/happendev/TestCapacitor

https://testapp.happen.zone/

1) Install app for the first time. The app works. It loads the files from the site and appears to install a service worker for offline. Plugins work.
2) Restart the app, the app loads the files from the service worker's offline cache. Capacitor does not seem to be initialized and as such plugins fail and the app breaks when they are used.

**Comment by dylanvdmerwe** [comment]
> if (Capacitor.isNativePlatform() && Capacitor.getPlatform() === 'android') {
>   const reboot = localStorage.getItem('reboot')
>   if (reboot !== '1') {
>     localStorage.setItem('reboot', '1')
>     setTimeout(() => location.reload(), 1)
>   } else {
>     localStorage.setItem('reboot', '0')
>   }
> }

Hi @xEsk, can you provide some more context, or a repo for this? I have tried, but even with this Capacitor is not initialized which means plugins don't work when loaded from the SW offline version. Any use of the plugins breaks.

**Comment by dylanvdmerwe** [comment]
![image](https://user-images.githubusercontent.com/2852839/154499453-67e22f9d-d726-4465-986c-576d2b20d041.png)

This is the cached PWA version of the app. 

As you can see, it detects that the platform is Android and isNativePlatform is true. But it has not initialized any android plugin stuff. 

Is there maybe a way to force Capacitor to run in 'web' mode here (as a true PWA), as then the plugins should work?

**Comment by Aarbel** [comment]
@dylanvdmerwe @webuniverseio @goforu @xEsk @chrisharris77 

Ay updates about this issue ?

**Comment by Aarbel** [comment]
> I'm facing this "problem" too....
> 
> As a temporary "workaround" (in order to solve this), I force a site reload when the ServiceWorker is Ready. I know and I also don't like the solution, but I needed to implement this 💩 while this "issue/bug/feature" is addressed.
> 
> ```
> if (Capacitor.isNativePlatform() && Capacitor.getPlatform() === 'android') {
>   const reboot = localStorage.getItem('reboot')
>   if (reboot !== '1') {
>     localStorage.setItem('reboot', '1')
>     setTimeout(() => location.reload(), 1)
>   } else {
>     localStorage.setItem('reboot', '0')
>   }
> }
> ```
> 
> This code is working for me, at the time as I write this... (is working on production).
> 
> Forgive me... 😂

Is this part still working ? 
Do service workers also work with this fix ? (managing dynamic modules download)

Thanks a lot !

**Comment by dharmeshds** [comment]
Is there any permanent resolution to this issue to make service workers work with capacitor plugins on Android? It is very frustrating that my Ionic6/Angular13 app works nicely with the service worker on browser but fails to register the same on Android. When I implement the workaround suggested, service worker loads but capacitor plugins fail to load on the device. Please update when there is any resolution or workaround for this.

**Comment by Aarbel** [comment]
@jcesarmobile 

Do you need a budget to priorise this issue ?

**Comment by BraulioMonroy** [comment]
ffs 
![image](https://user-images.githubusercontent.com/91504823/161114759-b28c70f9-f66c-4083-99cb-5cbb7b856941.png)

**Comment by Aarbel** [comment]
Still nobody found a solution here ?

**Comment by yoyo930021** [comment]
I using this answer and work for me on android.
https://stackoverflow.com/questions/55894716/how-to-package-a-hosted-web-app-with-ionic-capacitor/55916297#55916297

but I replace `ServiceWorkerController` to `ServiceWorkerControllerCompat` for my case.

**Comment by Aarbel** [comment]
Thanks a lot @yoyo930021 

I'm ready to pay someone as freelance  to develop the supported module / fix for capacitor.
Who wants here ?

**Comment by Aarbel** [comment]
@jcesarmobile

Any info about updates on this issue ? Can we sponsor the fix ?

**Comment by Aarbel** [comment]
@jcesarmobile

Any info about updates on this issue ? Can we sponsor the fix ?

**Comment by Aarbel** [comment]
> I using this answer and work for me on android with capacitor 2. https://stackoverflow.com/questions/55894716/how-to-package-a-hosted-web-app-with-ionic-capacitor/55916297#55916297
> 
> but I replace `ServiceWorkerController` to `ServiceWorkerControllerCompat` for my case.

Works also on iOS ?

**Comment by petermakeswebsites** [comment]
I would very much appreciate an externally hosted server PWA setup to interface properly with Capacitor's plugins on iOS. I wonder if anyone above has come across any solutions?

**Comment by teacoat** [comment]
Something similar is happening to me, I've deployed my angular app to my server and I am getting some very weird behavior.
Works perfectly locally, but, I'm trying the following code:
![image](https://user-images.githubusercontent.com/3913019/178172313-f93dd89a-cecd-4ed4-abd5-f2315789c24b.png)

Here it is in the web app:
![image](https://user-images.githubusercontent.com/3913019/178172256-62344f00-b0e4-450c-a652-30cea74b1ec4.png)

Here it is in the emulator:
![image](https://user-images.githubusercontent.com/3913019/178172360-761ac2e0-f8c1-4b97-adfc-5ffe77b726fa.png)

No idea what is happening here. It makes no sense and I've been trying to tweak configs for 8 hours at this point.

**Comment by yoyo930021** [comment]
I find a solution in Android.

1. Add code in Native:
I using this answer and work for me on android with capacitor 2. https://stackoverflow.com/questions/55894716/how-to-package-a-hosted-web-app-with-ionic-capacitor/55916297#55916297
but I replace ServiceWorkerController with ServiceWorkerControllerCompat for my case.

2. Add code in service worker:
```
const getRequestInit = async (request: Request) => ({
  method: request.method,
  headers: request.headers,
  body: ['GET', 'HEAD'].includes(request.method) ? undefined : await request.blob(),
  referrer: request.referrer,
  referrerPolicy: request.referrerPolicy,
  mode: request.mode,
  credentials: request.credentials,
  cache: request.cache,
  redirect: request.redirect,
  integrity: request.integrity
})

const addAcceptHeaderWhenNavigate = async (req: Request) => {
  const headers = new Headers(req.headers)
  headers.set('accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8')
  return new Request(req.url, { ...await getRequestInit(req), headers })
}

const HTMLStrategy = (): Strategy => {
  class NetworkReplaceHost extends NetworkOnly {
    async _handle (request: Request, handler: StrategyHandler) {
      return super._handle(
        await addAcceptHeaderWhenNavigate(request),
        handler
      )
    }
  }

  return new NetworkReplaceHost()
}

registerRoute(({ request }) => request.mode === 'navigate', HTMLStrategy())
```

It can solve [this problem](https://github.com/ionic-team/capacitor/issues/5278#issuecomment-1165442865).
PS. I use `workbox` in the service worker.

**Comment by Aarbel** [comment]
@yoyo930021 thanks a lot for your post, not solution yet on iOS ?

**Comment by yoyo930021** [comment]
> @yoyo930021 thanks a lot for your post, not solution yet on iOS ?

I can't enable service workers in my iOS app WKWebview, so I don't research it.

**Comment by Aarbel** [comment]
@yoyo930021 normally service workers are working on Ca[acitor wkwebview, which problems are you facing on this subject ?

**Comment by yoyo930021** [comment]
@Aarbel @dylanvdmerwe 
You must to use app bound domains.
https://webkit.org/blog/10882/app-bound-domains/

He doesn't fit my needs, so I won't research it for now

**Comment by SkaveRat** [comment]
We're also running into this problem. The workaround with the Plugin doesn't seem to work for us. Not sure why, and I can't see a way to check what goes wrong.

I had to convert the kotlin code above to java, so maybe something went wrong there? although the code does get called, when I hook the android debugger to it.

The Plugin java code:

```java
@CapacitorPlugin
public class SetupPlugin extends Plugin {

    @Override
    public void load() {
        super.load();

        // Fix Capacitor native bridge failed when reload page with service worker
        // https://github.com/ionic-team/capacitor/issues/5278

        if (WebViewFeature.isFeatureSupported(WebViewFeature.SERVICE_WORKER_BASIC_USAGE)) {
            ServiceWorkerControllerCompat swController = ServiceWorkerControllerCompat.getInstance();

            SetupPlugin that = this;

            swController.setServiceWorkerClient(new ServiceWorkerClientCompat() {
                @Nullable
                @Override
                public WebResourceResponse shouldInterceptRequest(@NonNull WebResourceRequest request) {
                    return that.bridge.getLocalServer().shouldInterceptRequest(request);
                    // This line is called, but returns null
                }
            });
        }
    }
}
```

The `return` returns `null` on a request to `[domain]/sw.js` and I feel this is wrong?

**Comment by Aarbel** [comment]
@jcesarmobile do you have any news about this ?

**Comment by leo-buneev** [comment]
Full working workaround with latest Capacitor and latest Android - compiled from ideas of @yoyo930021

```
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    
    if(Build.VERSION.SDK_INT >= 24 ){
      ServiceWorkerController swController = ServiceWorkerController.getInstance();

      swController.setServiceWorkerClient(new ServiceWorkerClient() {
        @Override
        public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
          if(request.getUrl().toString().contains("index.html")) {
            // Hack to help capacitor's "shouldInterceptRequest"
            request.getRequestHeaders().put("Accept", "text/html");
          }
          var result =  bridge.getLocalServer().shouldInterceptRequest(request);
          return result;
        }
      });
    }
  }
}
```

Note that depending on your SW setup root file may not be called "index.html". In that case feel free to adjust `if(request.getUrl().toString().contains("index.html"))` condition above according to your app's setup

**Comment by m3di** [comment]
im using capacitor v4 and still got the issue, non of the solutions worked for me :(

**Comment by mlynch** [comment]
I am testing this right now in Capacitor v4, Chrome WebView v101, and this is working just fine for me:

```java
public class MainActivity extends BridgeActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ServiceWorkerController swController = ServiceWorkerController.getInstance();

        swController.setServiceWorkerClient(new ServiceWorkerClient() {
            @Nullable
            @Override
            public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
                return bridge.getLocalServer().shouldInterceptRequest(request);
            }
        });
    }
}
```

Am I missing something for why this approach isn't working for others? My emulator is Android 13 (API 33)

**Comment by yoyo930021** [comment]
> 

It will happen when precache in service worker.
In most case, we use `workbox` for service worker.
https://web.dev/precache-with-workbox/

When precache, the request doesn't have `accept` header with html file.

**Comment by yoyo930021** [comment]
> On Android, I am testing this right now in Capacitor v4, Chrome WebView v101, Android 13 emulator (API 33), and this is working just fine for me:
> 
> ```java
> public class MainActivity extends BridgeActivity {
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
> 
>         ServiceWorkerController swController = ServiceWorkerController.getInstance();
> 
>         swController.setServiceWorkerClient(new ServiceWorkerClient() {
>             @Nullable
>             @Override
>             public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
>                 return bridge.getLocalServer().shouldInterceptRequest(request);
>             }
>         });
>     }
> }
> ```
> 
> With this I am able to load a remote URL (not localhost), and have it access plugins which are correctly defined and routed to native plugin code.
> 
> Am I missing something for why this approach isn't working for others? cc @dylanvdmerwe


It will happen when precache in service worker.
In most case, we use `workbox` for service worker.
https://web.dev/precache-with-workbox/

When precache, the request doesn't have `accept` header with html file.

**Comment by mlynch** [comment]
@yoyo930021 I'll play around with the precaching stuff. I'm using workbox (using [next-pwa](https://github.com/shadowwalker/next-pwa))

**Comment by yoyo930021** [comment]
> @yoyo930021 I'll play around with the precaching stuff. I'm using workbox (using [next-pwa](https://github.com/shadowwalker/next-pwa))

If you try to reload page after open?
In my test, It's no service worker when open app.
But if you waiting 1-3 minute and `window.location.reload`, It will work.

**Comment by mlynch** [comment]
@yoyo930021 with that snippet it works always. App launch, reloading the app, later app launches, etc.

Want to try my sample? https://github.com/mlynch/capacitor-remote-offline-example

**Comment by dylanvdmerwe** [comment]
@mlynch On Android and iOS through a service worker?

**Comment by mlynch** [comment]
@dylanvdmerwe I just tested iOS using app bound domains, can confirm assets are loaded from service worker, and native plugin access works just fine.

I'm not an expert with SW's though, only using the defaults in next-pwa: https://github.com/shadowwalker/next-pwa

But all appears to be working

**Comment by yoyo930021** [comment]
> @yoyo930021 with that snippet it works always. App launch, reloading the app, later app launches, etc.
> 
> Want to try my sample? https://github.com/mlynch/capacitor-remote-offline-example

The reason is `next-pwa`.
Next is a ssr framework, so it will not cache `index.html` by default.
See https://github.com/shadowwalker/next-pwa#available-options
`cacheStartUrl` `dynamicStartUrl` option and https://github.com/shadowwalker/next-pwa/blob/master/index.js#L168
![截圖 2023-01-11 下午3 32 10](https://user-images.githubusercontent.com/9126398/211744637-ce1edf99-2240-417f-b609-24f7a109cfc2.png)

**Comment by mlynch** [comment]
What would you recommend for default options? Looks like `cacheStartUrl` is `true` by default, and `dynamicStartUrl` is false which makes sense to me, but I can try different options. Is there a good angular sample I can try?

If there's some sort of middle ground here where we can recommend a SW configuration where this works, that seems like a decent path forward.

**Comment by yoyo930021** [comment]
> What would you recommend for default options? Looks like `cacheStartUrl` is `true` by default, and `dynamicStartUrl` is false which makes sense to me, but I can try different options. Is there a good angular sample I can try?

You can repro this case with `cacheStartUrl` is `true` by default, and `dynamicStartUrl` is false.

> If there's some sort of middle ground here where we can recommend a SW configuration where this works, that seems like a decent path forward.

We always cache index.html except SSR. I don't think this is practical.

**Comment by mlynch** [comment]
Okay, I can reproduce with that setting. I need to think more about this. 

What do you think the majority of Next.js users would want for this setting? They are likely serving dynamic index content, so having `dynamicStartUrl` true seems like a decent middle ground to get this working. Or maybe there's another way to inject some JS on the client that makes some call the web view can understand to inject capacitor? Not sure

**Comment by yoyo930021** [comment]
> Okay, I can reproduce with that setting. I need to think more about this. 
> 
> What do you think the majority of Next.js users would want for this setting? They are likely serving dynamic index content, so having `dynamicStartUrl` true seems like a decent middle ground to get this working. Or maybe there's another way to inject some JS on the client that makes some call the web view can understand to inject capacitor? Not sure

In next.js or SSR, It is reasonable not to cache HTML.
In SPA or offline APP, it need to cache HTML.

I think a way to inject some code in HTML. Maybe can slove it.

**Comment by mlynch** [comment]
I guess that begs the question to me: if you're building an SPA, then why do you need to have it loaded remotely in the first place? That would be a great use case for packaging locally inside the app

**Comment by leo-buneev** [comment]
For us, the usecase is the ability to switch between different SPA application builds (e.g. test/prod, or customer1/customer2) without recompiling wrapper application.

Also, more importantly - delivering updates without recompiling / updating wrapper application on app stores

**Comment by mlynch** [comment]
Thanks, that's helpful. At the moment I'm not sure how to get this working for your usecase. You would probably be well served with [Live Updates](https://ionic.io/docs/appflow/deploy/intro) which would let you do all of that and keep a fast local experience. For now I think I'm going to caveat the service worker experience with this trade-off which should work for a lot of users but not all, until we figure out how this will work. It might be a fundamental limitation of Android that we can't get around, I'm not sure.

**Comment by dylanvdmerwe** [comment]
Hi @mlynch 

We have a system that is rebranded based on different criteria, but is the same codebase. Right now, we have deployed this as an Angular site through Capacitor to each of the respective clients. Instead of using a codepush-like system or doing a full manual release each time, the idea would be to host the site ONCE as a simple PWA. 

In this way, multiple capacitor apps will all be pointing towards a single URL. Any deployments made to that single site, would then be pulled through (via the PWA SW) on each app and then be cached for future use. It would be really really seamless and work wonderfully. 

This was the cruz of me logging this entire issue. PWA hosting, running the Angular app and everything through Capacitor (Angular and iOS) works well and the capacitor native plugins work as expected. However as soon as the browser running within Capacitor has cached the assets, the next time the app runs the native plugins do not kick in. 

This issue is talking about the Capacitor plugins on a server.url site, once the PWA is cached locally from the service worker, never initialize.

![image](https://user-images.githubusercontent.com/2852839/212550313-fb33a15d-79aa-474f-9ffb-4e535954e2d3.png)

**Comment by mlynch** [comment]
@dylanvdmerwe Thanks for the additional context, very helpful. What I'm seeing is that SWs and caching, with Capacitor, _does_ work in some cases, so I'm trying to narrow down the exact setup that fails and what works, so we can document it if there's no fix we can make.

For example, I'm finding Next.js + next-pwa defaults enable this to work, and that would likely to apply to a ton of Next sites which is obviously a quite popular approach! But still interested in finding a fix for your approach

**Comment by perpetuallight** [comment]
@mlynch I think I have narrowed it down some more. I am hoping someone knows of a solution or understands why what I found is the case better than me. I thought caching would be a good option to pursue too but when I tried ``` bridge.getWebView().getSettings().setCacheMode(LOAD_NO_CACHE); ``` I still get the same result. 

I am using WebView version 109.

And I implemented the ServiceWorkerClient intercepter. This got the service worker to load every time but still results in injection failure on reload, Unless:

The only way that I can find to not have to reinstall, as mentioned above, is to enable the [Bypass for Network](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBypassServiceWorker) option from devtools. It should be a checkbox @ ``` Application->Service Workers ```.

Now I have been looking for the locally accessible port to access the protocol exposed by ``` webContentsDebuggingEnabled ``` on the WebView option to no avail. If anyone knows this golden piece of information I would be very grateful. 

Not having that I have been looking for the same setting from the WebView or WebViewClient or WebSetttings API. No luck their either. 

Which leaves me at the acceptance stage and considering a drastic hack. 

Since I can't modify the cache I will try to un-register the service worker on destroy. My experience is that a lot of users have the strange habit of not destroying their windows and not even rebooting occasionally. So I imagine the hack will not come into play too often.

My hope is that considering this perspective will inspire someone on this project to see it from a different angle and know of a better way to either get the flag enabled or a better way that doesn't require it to be enabled. Possibly derived from a better understanding of the caching problem or where the cache can be more atomically controlled.

**Comment by perpetuallight** [comment]
@mlynch Nevermind, I got it. This works to disable the cache for both proxy-able routes:

```
bridge.getWebView().getSettings().setCacheMode(LOAD_NO_CACHE);
ServiceWorkerController swc = ServiceWorkerController.getInstance();
swc.getServiceWorkerWebSettings().setCacheMode(LOAD_NO_CACHE);
swc.setServiceWorkerClient(new ServiceWorkerClient() {
      @Override
      public WebResourceResponse shouldInterceptRequest(WebResourceRequest req) {
        return bridge.getLocalServer().shouldInterceptRequest(req);
      }
});
```

Might not be viable for everyone but should be good for me and anyone else that are is using a 3rd party service worker pre-loader that doesn't offer necessary config options.

**Comment by perpetuallight** [comment]
Update: blocking network loads like so ``` [ServiceWorkerController].getServiceWorkerWebSettings().setBlockNetworkLoads(true); ``` seems to consistently prevent the service worker from intercepting network requests. But looking at its state in devtools shows that it gets stuck in the "trying to install" state and the network tab shows that the service worker failed to load due to CACHE_MISS. I wonder if this is because of the ``` Service-Worker: script ``` in the request headers.

If there is anyone else using the 3rd party service worker for something other than caching I would be interested to know if it will load the other features without the request header present while "blocking network loads".

It is not super clear how some of these settings are supposed to behave from the documentation. So I am trying to infer what I can.

**Comment by perpetuallight** [comment]
Update: I was assuming that the Service-Worker: script header was coming from the server but it was in the request. So I removed it and it did still run just without the conventional semantic understanding from the browser. Possibly observed another side effect that appears to cause the caching logic to infinitely loop on itself, at least in my particular 3rd party worker.

Then I decided to modify the Accept header to match the initial requests value which happened to have "text/html" in it while the worker was using "*/*". This was apparently what was preventing the Capacitor proxy from processing it.

In my case forcing the proxy to process it causes the server to return a bad status which luckily invalidates the cache entry(injected JS and all) and forces the network pull. All while leaving the rest of the cached resources intact and valid. 

So this will work for me. And I imagine it will help someone else too since breaking one html files' cache entry won't impact performance too much and I have never really seen the service worker cache work offline in a PWA anyway. But if that is a deal breaker for ya then this isn't for you.

**Comment by cyprian-nziim** [comment]
> When the Android app is first installed you can see Capacitor is working: ![image](https://user-images.githubusercontent.com/2852839/144424927-ab3a285a-5657-410d-9ac7-7884e626a8e7.png)
> 
> The site files are downloaded and served directly on first run: ![image](https://user-images.githubusercontent.com/2852839/144425080-1e5f7996-abb3-458d-9fa0-8241dc73c6e6.png)
> 
> When the app is launched the second time, Capacitor is not injected: ![image](https://user-images.githubusercontent.com/2852839/144425322-84ca66f3-8d20-45cc-8bd0-141e7f9dcecf.png)
> 
> The files are now served from the service worker: ![image](https://user-images.githubusercontent.com/2852839/144425625-e3f91a53-c29c-4342-8ec6-1ae4ad589b1a.png)
> 
> ![image](https://user-images.githubusercontent.com/2852839/144427772-8cc5619f-3db1-4d25-8bba-4f754dc31327.png)

Had this sam issue,

This worked for me. I just have to check if platform is Android, then I reloadForCapacitorInjection.
Hope this helps.
Thanks for all your inputs above.

`reloadForCapacitorInjection(){
    const scripts = document.querySelectorAll("head script[type='text/javascript']:not([src])");
    // console.log(scripts);
    console.log('Looking for Script with Capacitor')
    let matches = [];

    if(scripts.length) {

      scripts.forEach((script, index) => {
        
        if (script && script.textContent?.includes("Capacitor")) { 
          matches.push(script);
          console.log('found Script with Capacitor')
        } else if(index+1 == scripts.length && matches.length < 1) {
          console.log('reloading no Capacitor')
          location.reload();
        }
  
      })
      
    } else {
      console.log('reloading no Capacitor')
      location.reload();
    }

  }`

**Comment by kyllerss** [comment]
I am also impacted by this. Any updates on whether or not this is on the roadmap? Thanks!

**Comment by shahrukh1990** [comment]
I am also facing same issue. I have removed the service worker from my code. Still same.
Any idea?

**Comment by pspaulding** [comment]
Thanks @yoyo930021 , I just tried it again and it did not work.  Java is not my forte, but when I do the following:

```java
public class MainActivity extends BridgeActivity {
    private static final String TAG = "myapp";
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
Log.v(TAG, "SDK_INT:" + Build.VERSION.SDK_INT);
        if (Build.VERSION.SDK_INT >= 24) {
            ServiceWorkerController swController = ServiceWorkerController.getInstance();

            swController.setServiceWorkerClient(new ServiceWorkerClient() {
                @Override
                public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
                    Log.v(TAG, request.getUrl().toString());
                    if (request.getUrl().toString().contains("index.html")) {
                        request.getRequestHeaders().put("Accept", "text/html");
                    }
                    var result = bridge.getLocalServer().shouldInterceptRequest(request);
                    return result;
                }
            });
        }
    }
}
```

the first `Log.v` logs "SDK_INT:30" in Logcat, but the second `Log.v(TAG, request.getUrl().toString());` is never called.

**Comment by pspaulding** [comment]
Oops, just realized it wasn't logging because I had just disabled the service worker.  Too many moving parts, LOL.  The investigation continues...

**Comment by henry-alakazhang** [comment]
Hey everyone. I also ran into this issue a while ago, but successfully worked around it by adding the `Accept: text/html` header. (I also had to work around the Angular service worker hash checks by rewriting the ngsw.json, but that's a separate story). In testing and in most cases, the app works fine now. First load downloads the app normally; the service worker registers itself; second load is from service worker cache and the Capacitor runtime is injected as it should be.

However, in the wild, I've got a very high volume Sentry error reporting that `"XYZ" Plugin is not implemented on android`. These are definitely coming from Android users on the latest version of the app and website, but it doesn't happen consistently. Other telemetry tells me the same users are able to use the app at least some of the time.

Has anyone else run into this? The same issue where the runtime isn't injected, but flaky instead of all the time. If not, I guess there must be something wrong inside our service wrapper setup.

**Comment by Aarbel** [comment]
> Accept: text/html

Thanks a lot Henry, can give us more details about where you add the `Accept: text/html` header ?

**Comment by yoyo930021** [comment]
I suggest not attempting to enable service workers in capacitor android. Although there are various hacks available to make it function to some extent, in reality, it performs poorly.

Known issues:
1. Service worker requests do not use a custom user agent.
2. The service worker is re-established every time the app is launched and is only useful during the current app lifecycle.

**Comment by toriphes** [comment]
After working several hours on this I ended up with this solution working on capacitor 5.
Hope this can help someone.

```java
public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
      ServiceWorkerController swController = null;
      swController = ServiceWorkerController.getInstance();

      swController.setServiceWorkerClient(new ServiceWorkerClient() {
        @Override
        public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
          if (request.getUrl().toString().contains("index.html")) {
            request.getRequestHeaders().put("Accept", "text/html");
          }
          return bridge.getLocalServer().shouldInterceptRequest(request);
        }
      });
    }
  }
}
```

**Comment by leo-buneev** [comment]
> 2. The service worker is re-established every time the app is launched and is only useful during the current app lifecycle.

Just for info - I can't confirm that. We're using SW successfully (with `text/html` workaround) on capacitor(v4) android with remote URL to store application files, and it works offline after app restart. So it's useful not only during app lifecycle.

**Comment by COBRASoft5** [comment]
What about iOS? Does the service worker work the same as on Android within Capacitor ?

**Comment by perpetuallight** [comment]
I thought service workers were a staple of PWA's? The user-agent could be part of the problem. I remember considering that when I was working on this. Perhaps it can be addressed at the specification level.

**Comment by perpetuallight** [comment]
> I've tried several of the above suggestions, including various changes to MainActivity.java, and none of them worked. I am using Webpack 4 + sw-precache-webpack-plugin. The basic `window.Capacitor` functions work fine when using a service worker, but all the plugins (including `@capacitor/app`) fail to work. In my case, the stripe-terminal plugin that I am using only makes sense to use when the application is online, and only a subset of our users need the functionality provided by the plugin.
> 
> I've also tried isolating all use of the plugin to a separate entry point that is not managed by the service worker, and loading it as an ES module ahead of the application. Still no luck (probably because the index.html is managed by a service worker). I imagine those who are more knowledgeable about Capacitor are laughing at me right now.
> 
> My hack which others may be able to use is to toggle the service worker on/off by anticipating the user's needs (and reloading). This is far from ideal, as it means the users that depend on the plugin do not benefit from a service worker for the 95% of the time that they are not using the plugin's functionality.
> 
> Overall, using Capacitor has been a positive experience. I just feel a bit uneasy as my primary reason for switching from Cordova (which worked fine with service workers) to Capacitor was for this particular plugin.

In your case, I think stripe uses service workers anyway. I could be wrong, but I seem to remember that being the case. So you may want to try the same proxy slice but load something else instead when offline? The proxy slice I am referring to is the same one everyone seems to be using but modified for your case.

**Comment by perpetuallight** [comment]
It seems like these edge cases are going to be quite difficult to work with in Capacitor in general due to how the proxy is done. Maybe the better fix is to simply add something to the documentation about when/why/how to bypass the proxy to handle a given edge case?

**Comment by Erudition** [comment]
If it's not supported that's fine, but [the Capacitor docs literally suggest using a Service Worker](https://capacitorjs.com/docs/web/progressive-web-apps#service-worker) to make the webapp progressive when it's run in-browser, with no hint that it will break plugin functionality when run on native mobile.

Perhaps we can add certain Capacitor-injection paths to a service worker's interception "exception list"?

**Comment by Erudition** [comment]
> 2\. The service worker is re-established every time the app is launched and is only useful during the current app lifecycle.

Actually, the service worker stays established and persists between sessions so long as the webview's storage is not cleared - in fact it's only on the second load of the page (with SW serving interceptions) that all my Capacitor plugins crash.

If there are specific Capacitor injection scripts that we need to blocklist, that would be a good solution for now!

**Comment by bosung90** [comment]
Would be nice to have this included as part of Capacitor by default, many people will be able to save time.
https://github.com/ionic-team/capacitor/issues/5278#issuecomment-1313531876

**Comment by ZeroHackeR** [comment]
> After working several hours on this I ended up with this solution working on capacitor 5. Hope this can help someone.
> 
> ```java
> public class MainActivity extends BridgeActivity {
> 
>   @Override
>   public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
> 
>     if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
>       ServiceWorkerController swController = null;
>       swController = ServiceWorkerController.getInstance();
> 
>       swController.setServiceWorkerClient(new ServiceWorkerClient() {
>         @Override
>         public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
>           if (request.getUrl().toString().contains("index.html")) {
>             request.getRequestHeaders().put("Accept", "text/html");
>           }
>           return bridge.getLocalServer().shouldInterceptRequest(request);
>         }
>       });
>     }
>   }
> }
> ```

Hello everyone! :)

I am having a similar issue.
1) I downloaded an html file to app's data folder. 
2) Then, I used Capacitor.convertFileSrc to load the html file.
3) The HTML was loaded. However, Capacitor scripts were not being injected.

How do I fix the issue? Please help! :( 

PS. already tried above codes and it didn't help.

**Comment by christian-kolb** [comment]
It doesn't look like the team will add official support for running a production environment via server.url. I just stumbled over https://capgo.app as an alternative to not have to worry about backwards compatibility. Maybe it's relevant for a few of you 🙂

**Comment by Erudition** [comment]
@mlynch 
> You would probably be well served with [Live Updates](https://ionic.io/docs/appflow/deploy/intro) which would let you do all of that and keep a fast local experience.

Unfortunately I'm not able to include proprietary software or services in my app. I just want to update as soon as my CI builds a new static app on github pages, saving the app store updates for plugin changes - but also have offline support which Service Workers are perfect for (and is already working well in browsers).

Since none of the workarounds here are working (unless you do SSR), in the mean time I will try to have a local startup file that grabs Capacitor and then hands it off to the app somehow

**Comment by wmenegali** [comment]
@jcesarmobile any date estimate on when the fix will be merged and available? Also stuck on this and none of the above workarounds are working.

**Comment by Aarbel** [comment]
Thanks a lot @jcesarmobile for the update ;)
