### ISSUE TITLE
[Bug]: Android 15 enforces edge-to-edge

### ISSUE THREAD

**Issue by JumBay** [ionic-team/capacitor#7804]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

In Android 15 the [navigation bar overlaps the app](https://medium.com/androiddevelopers/insets-handling-tips-for-android-15s-edge-to-edge-enforcement-872774e8839b). My users a reporting it https://github.com/wako-app/wako/issues/121
This seems to be different to https://github.com/ionic-team/capacitor/issues/6423, that's why I open a new issue.

### Expected Behavior

The navigation bars shouldn't overlap

### Project Reproduction

-

**Comment by JumBay** [comment]
Yes I've seen it, but it should work without it

**Comment by JanPolasek** [comment]
This is the same issue as https://github.com/ionic-team/capacitor/issues/6423, except in in Android 13 edge to edge was opt-in while in Android 15 it becomes opt-out, but it is the same issue nonetheless. And since the only way to opt-out on Android 15 is getting immediately deprecated, there really should be a 1st party solution, otherwise capacitor will become quite literally unusable without using 3rd party plugins (or writing one yourself) and that's not a great place to be at.

To be honest this is actually something *Google* should fix. The way safe areas are supposed to be handled on web is via standard CSS `env(safe-area-inset-*)` variables which are supported everywhere *except* for Android System WebView which still doesn't support them and simply reports all of the insets as 0px. Unfortunately given the activity this issue has seen in the chromium issue tracker and the general sorry state of the android webview I don't think we'll ever see it fixed there https://issues.chromium.org/issues/40699457.

One option to get it working for now is something like the aforementioned [@capacitor-community/safe-area](https://github.com/capacitor-community/safe-area) (though there are some issues with that one that I've opened a PR for, so I don't consider it a solution just yet, but it's close) which solves this by adding the insets via `--safe-area-inset-*` CSS variables since it cannot touch the `env()` variables.

Another, albeit temporary, alternative is to restore the previous behaviour with
```xml
<application
    android:windowOptOutEdgeToEdgeEnforcement="true"
    ...>
    ...
</application>
```

**Comment by danpercic86** [comment]
I have the same issue and nothing works for me, unable to update to capacitor 7 until official support for edge-to-edge is added

**Comment by ckoon-infopro** [comment]
Please let us know if there are any plans to address this in Capacitor. For now, we can either opt out or use [@capacitor-community/safe-area](https://github.com/capacitor-community/safe-area). I have tested both options, and they both worked.

**Comment by bohdanovdmytro** [comment]
same here

**Comment by eduardoRoth** [comment]
For me adding `android:windowOptOutEdgeToEdgeEnforcement="false"` in the application node of the app main `AndroidManifest.xml` works

**Comment by mla03** [comment]
> I don't think this is something that Capacitor should fix since you have to deal with safe areas like these on iOS as well. I use the @aashu-dubey/capacitor-statusbar-safe-area plugin and this works fine with the below tweaks.
> 
> I think the focus should probably be on properly supporting safe area insets on Android in Capacitor so we don't need to use a plugin, and only applying the bottom safe area if the navigation bar is actually set to overlap the webview.
> 
> I have this in MainActivity.java. I think this is the most important part for getting the safe areas to work correctly (with a safe area plugin). Without this the layout is cooked.
> 
> ```
> @Override
>   protected void onCreate(Bundle savedInstanceState) {
>       super.onCreate(savedInstanceState);
>       Window window = getWindow();
>       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
>         window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
>                 | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
>                 | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
>       }
>   } 
> ```
> 
> With the above snippet 😍 (and using safe areas in my layout):
> 
> <img alt="Image" width="766" src="https://private-user-images.githubusercontent.com/19263848/408899606-69228e8d-ac0e-456d-97f4-97a7c998e04e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1NjkwNDYsIm5iZiI6MTczODU2ODc0NiwicGF0aCI6Ii8xOTI2Mzg0OC80MDg4OTk2MDYtNjkyMjhlOGQtYWMwZS00NTZkLTk3ZjQtOTdhN2M5OThlMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjAzVDA3NDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNGJmOGE1ZmIwOThlN2JiN2YwMTY1NTg2ZDkzZWM3NmFhOTkwY2JiNTVkNGM1YWUyZWRhZGMyZDllYjI3YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BM_v7bAos7pE12EVwTKqj9NNgg3iVTTLHctgK2sJzZQ">
> Without the above snippet 🤢 (bottom safe area is detected even though the nav bar isn't overlapping the webview): <img alt="Image" width="618" src="https://private-user-images.githubusercontent.com/19263848/408899004-6b30ed01-dbac-4f75-a330-109c432e85e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1NjkwNDYsIm5iZiI6MTczODU2ODc0NiwicGF0aCI6Ii8xOTI2Mzg0OC80MDg4OTkwMDQtNmIzMGVkMDEtZGJhYy00Zjc1LWEzMzAtMTA5YzQzMmU4NWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjAzVDA3NDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZjllMjBiNDA2YmQ0NDUyNTlhNzEwMDYyODdjZDZkM2RiZjlhMGNlMWYyMDhiYjQ5YmU2NDBlNTMxOTNkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HFviW2w8thaxbGuwU0R2ZPjCsaEGj12HpW80uMmrrSU"> I also have the following specified in my AndroidManifest.xml:
> 
> ```
>         <activity
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
>             android:name=".MainActivity"
>             android:label="@string/title_activity_main"
>             android:theme="@style/AppTheme.NoActionBarLaunch"
>             android:windowSoftInputMode="adjustResize"
>             android:launchMode="singleTask"
>             android:screenOrientation="unspecified"
>             android:exported="true">
> ```
> 
> It seems that the android:windowSoftInputMode="adjustResize" property is important when it comes to getting the color of the nav buttons to automatically change depending on the background. It looks quite sexy because the bar is transparent but the button color is dynamic. If this is set for older API levels, the nav buttons will always have a black background.
> 
> Hope this info helps someone :)

In the addition to MainActivity, the "setSystemUiVisibility" is deprecated? 
"This constant was deprecated in API level 30.
Use [WindowInsetsController.hide(int)](https://developer.android.com/reference/android/view/WindowInsetsController#hide(int)) with [Type.statusBars()](https://developer.android.com/reference/android/view/WindowInsets.Type#statusBars()) instead."

**Comment by pjamessteven** [comment]
@mla03 you're right, I didn't notice that. I don't spend enough time in Android Studio! 

I updated my code with this method for newer API levels and it has the same effect.

         if (Build.VERSION.SDK_INT >= 30) {
                window.setDecorFitsSystemWindows(false);
        } else {
            window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
        }

**Comment by mla03** [comment]
@pjamessteven great. I've tried it, together with the `capacitor-community/safe-area`.

I set the margins of the footer and header in my global.scss:
`ion-header {
    margin-top: var(--safe-area-inset-top, 0px);
}

ion-footer {
    margin-bottom: var(--safe-area-inset-bottom, 0px);
}`

Still not perfect. 

![Image](https://github.com/user-attachments/assets/c9ae75e3-68a1-49f9-91c3-261bcf0dada4)

I still think that it's something for Ionic/Capacitor to fix, since reading the documentation for their ion-footer/ion-header states:
"_When a toolbar is used inside of a footer/header, the content will be adjusted so it is sized correctly, and **the footer/header will account for any device safe areas**._" 
https://ionicframework.com/docs/api/header
https://ionicframework.com/docs/api/footer

**Comment by pjamessteven** [comment]
Like with the navigation bar, you also need to set the menu bar to overlay
the web view when using safe areas. I can’t remember how I achieved this,
on mobile right now.

**Comment by pjamessteven** [comment]
@mla03 I just had a look and I'm using the following from the status bar plugin (https://capacitorjs.com/docs/apis/status-bar)

StatusBar.setOverlaysWebView({ overlay: true });

It would be nice if there was an official 'navigation-bar' plugin like the status bar plugin that would let you change whether the nav bar overviews the webview, the button and the background colors or transparency... and it would be even nicer if these plugins automatically injected the correct safe areas for your preferences as css variables. Thoughts?

**Comment by robingenz** [comment]
I've just published the [Android Edge-to-Edge Support](https://capawesome.io/plugins/android-edge-to-edge-support/) plugin, which applies an insert to the web view to restore the previous look. You just need to install it, and your done:

```bash
npm i @capawesome/capacitor-android-edge-to-edge-support
```

Optionally, you can also change the background color of the status and navigation bar. Let me know if you encounter any problems by creating an issue or discussion in [capawesome-team/capacitor-plugins](https://github.com/capawesome-team/capacitor-plugins).

**Comment by markemer** [comment]
Should be solved in #7871

**Comment by mqrten** [comment]
> I've just published the [Android Edge-to-Edge Support](https://capawesome.io/plugins/android-edge-to-edge-support/) plugin, which applies an insert to the web view to restore the previous look. You just need to install it, and your done:
> 
> npm i @capawesome/capacitor-android-edge-to-edge-support
> Optionally, you can also change the background color of the status and navigation bar. Let me know if you encounter any problems by creating an issue or discussion in [capawesome-team/capacitor-plugins](https://github.com/capawesome-team/capacitor-plugins).

Only solution that actually works for me

**Comment by baxxos** [comment]
I've stumbled upon this thread since I'm dealing with the forced edge-to-edge mode in Android WebView app. We already have an existing solution for iOS which is very elegant and relies on adding paddings equal to the `env(safe-area-inset-*)` values (as mentioned by @JanPolasek above)

My question is - what is the recommended way we're supposed to do this in WebView apps? Obviously, Ionic and capacitor somehow solve it here, but isn't it just a workaround for something that should be fixed by the Android team themselves?

Sorry for hijacking this, I'm just getting a bit lost here and the Android docs have not been very helpful so far.

**Comment by kwebdev11** [comment]
> I've just published the [Android Edge-to-Edge Support](https://capawesome.io/plugins/android-edge-to-edge-support/) plugin, which applies an insert to the web view to restore the previous look. You just need to install it, and your done:
> 
> npm i @capawesome/capacitor-android-edge-to-edge-support
> Optionally, you can also change the background color of the status and navigation bar. Let me know if you encounter any problems by creating an issue or discussion in [capawesome-team/capacitor-plugins](https://github.com/capawesome-team/capacitor-plugins).

Thankyou @robingenz , only solution that resolved the issue of **StatusBar overlapping on app** OR **app starting from the edge-to-edge of the mobile screen** ( Issue occur after updating into Capacitor 7 targeting android 15 ).

I just install the package `npm install @capawesome/capacitor-android-edge-to-edge-support
npx cap sync` and run the `npx cap sync` . And the test on simulator as well as on physical device. It works fine.

**Comment by Yernike** [comment]
I also solved it with @capawesome/capacitor-android-edge-to-edge-support, but if I set the background to white, on Android 15, the navigation buttons are also white. Does anyone know how to fix this?

I have an advertisement banner at the bottom (AdMob) with a margin. This margin is incorrect only on Android 15 because it starts from the bottom of the device instead of from the navigation bar. The margin is setted on TypeScript.

**Comment by AlfonsoMobilia** [comment]
Hello!

In our case, we solved it using @capawesome/capacitor-android-edge-to-edge-support. We tested it, and it works fine on Android 14, 15, and 16, but we had to adjust a few things:

capacitor.config.json
```
EdgeToEdge: {
    backgroundColor: "#000000",
}
```

app.component.ts (in the constructor)
```
const setBackgroundColor = async () => {
    await EdgeToEdge.setBackgroundColor({ color: '#000000' });
    await StatusBar.setStyle({ style: Style.Dark });
};
setBackgroundColor;
```

Thank you very much!
